name: isport_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts: 
    - family: Toboggan
      fonts:
        - asset: assets/fonts/Toboggan-Light.otf
          weight: 400
        - asset: assets/fonts/Toboggan-MediumItalic.otf
          weight: 700
    - family: Toboggan-Medium
      fonts:
      - asset: assets/fonts/Toboggan-Medium.ttf
        weight: 500
    
  assets:
    - assets/images/google.png
    - assets/images/telegram.png
    - assets/images/apple.png
    - assets/images/facebook.png